title: byRobinGames
description: Stencyl Extensions
show_downloads: true
google_analytics:
remote_theme: pmarsceill/just-the-docs

html_pages:

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
